### PR TITLE
Python3 anuga py3

### PR DESCRIPTION
**Pull request by uniomni**
Work related to Towradgi + fixing two new tests failures under Python3.8. All pass now.

### CODE REVIEW

**Comment by uniomni** [comment]
Still some issues with the parallel tests....

**Comment by stoiver** [comment]
@uniomni  Strangely the travis ci tests are passing on the parallel tests. THey are using a clean installation of ubuntu 18.04. It is quite mysterious.

**Comment by stoiver** [comment]
@uniomni here is a link to the travis ci tests https://travis-ci.org/github/stoiver/anuga_core

**Comment by uniomni** [comment]
OK thx

**Comment by uniomni** [comment]
Mysterious. I might set up a virtual machine with ubuntu 18.04 then....

**Pull request merged**
