### PR TITLE
Update swDE_domain.c

### PR DESCRIPTION
**Pull request by samcom12**
fixed installation related issues

### CODE REVIEW

**Comment by stoiver** [comment]
@samcom12 it seems that your code is still creating some problems with the unittests. But I had a look at your code and copied over some of your changes to the `develop_de1_fast` branch. 

I did notice that you nested some `#pragma omp parallel` Does this help at all with improving speed? seemed like the inner loop was very short. 

I found the error with accumulating the boundary flux. 

I have also made a quite a change to the file structure in the `anuga/shallow_water` directory. In particular I have broken up the file `swDE_domain.c` into `swDE_domain_original.c`,  `swDE_domain_local_timestep.c`and `swDE_domain_openmp.c` corresponding to domain parameter `multiprocessor_mode` equal to 0,1,2 respectively. 

The idea is that we will create a separate `swDE_domain_cuda.c` when we work on the GPU version.

With the changes now the unittests (`pytest --pyargs anuga` )  pass with  `multiprocessor_mode` set to 0,1 and 2.

Using `multiprocessor_mode = 2` with my `run_anuga_rectangle.py`  script on my surface pro 4 with 4 cores using wsl I get

OMP_NUM_THREADS=1  56.14 s
OMP_NUM_THREADS=4  25.95 s

In comparison, with the original code I get 50.14 s

Would be good to see how the code works on a machine with more cores.

**Comment by samcom12** [comment]
@stoiver If each iteration of inner loop is taking substantial amoun of time, then we can use nested parallelism with OpenMP. Otherwise, we can use openmp pragmas only for outer loop reducing complexity.

Could you share your script `run_anuga_rectangle.py` so I can quickly run it on cluster?

Also, with latest changes to `develop_de1_fast` branch, I still see some errors with  `python test_DE_openmp.py`



```
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   utkarsh
  Local device: mlx5_0
--------------------------------------------------------------------------

======================================================================
Test Riverwall
======================================================================
Evolve domain1
Time = 0.0000 (sec), steps=0 (0s)
Time = 0.1000 (sec), delta t = 0.05752178 (s), steps=2 (0s)
Evolve domain2
Time = 0.0000 (sec), steps=0 (0s)
Time = 0.1000 (sec), delta t = 0.05752178 (s), steps=2 (0s)
domain1 timestep  0.06391308536439723
domain2 timestep  0.06391308536439723
timestep error               0.0
stage explicit update error  0.0
xmom  explicit update error  0.0
ymom  explicit update error  0.0
edge timestep error          0.0
pressure work error          0.0
edge flux work error         0.0
.
======================================================================
Test Runup
======================================================================
Evolve domain1
Time = 0.0000 (sec), steps=0 (0s)
Time = 0.1000 (sec), delta t in [0.03784151, 0.03888021] (s), steps=3 (0s)
Evolve domain2
Time = 0.0000 (sec), steps=0 (0s)
Time = 0.1000 (sec), delta t in [0.03784151, 0.03888021] (s), steps=3 (0s)
domain1 timestep  0.04160448346451827
domain2 timestep  0.04160448346451827
timestep error               0.0
stage explicit update error  0.0
xmom  explicit update error  0.0
ymom  explicit update error  0.0
edge timestep error          0.0
pressure work error          0.0
edge flux work error         0.0
.
----------------------------------------------------------------------
Ran 2 tests in 0.274s

OK
```

**Comment by stoiver** [comment]
@samcom12 the output from `test_DE_openmp.py`  is actually fine. The `WARNING: There was an error initializing an OpenFabrics device` is independent of the code. The output from the script is showing that the errors are zero. So all fine. 

You can find my benchmark code  in the repository https://github.com/stoiver/anuga_pytest_benchmarks in the benchmarks directory. The command I ran was:

```
python run_anuga_rectangle.py --sqrtN 500
```
with various values of `OMP_NUM_THREADS` and various values of `multiprocessor_mode` set in `shallow_water_domain.py`

**Comment by samcom12** [comment]
@stoiver I benchmarked the same script varying `self.set_multiprocessor_mode(0)` from 0,1, and 2. The two runs one with OMP_NUM_THREADS=1 and 4. 
[rectangular_case_bench_openmp_and_multiprocesor.tar.gz]
(https://github.com/stoiver/anuga_core/files/11488872/rectangular_case_bench_openmp_and_multiprocesor.tar.gz)

:)

**Comment by stoiver** [comment]
@samcom12 thanks for the benchmark results. They are a little confusing. I notice that one of the runs has an evolve time of around 40s and the rest around 5s. I assume the 40s is associated with the original code as it is consistent with my result of 50s on my laptop. But the others all seem to be gaining the same speedup of around 8. I wonder if all those are using the full number of OMP threads?

I will change the benchmark code to take a `multiprocessor_mode` as an argument.

**Comment by stoiver** [comment]
@samcom12 just updated the `run_anuga_rectangular.py` so that it takes an extra argument `-mm` to allow multiprocessor_mode to be set to 0,1,2. 

The results for mode 0 and 1 should be about the same and should not be using OPENMP. Only mode 2 should be showing any speed up! (maybe your shallow_water_domain may be set to 2?)

With mode 2, with one thread the result should be a bit slower than the mode 0 and 1 results. Hopefully we gain as you increase the number of OMP threads.

**Pull request closed without merging**
